"""
Copy the inference runtime and the trained model into the Sound Guardian app
(python/edge_audio/) so the App Lab container can classify audio itself.

    python deploy.py                 # -> ../python/edge_audio/
    python deploy.py /some/other/dir

Only the numpy + TFLite runtime goes across (no TensorFlow): config.py,
features.py, infer_wav.py, unoq_stream.py, model_int8.tflite, labels.txt.
Run it again after every retrain. The copy is generated; edit the originals here.
"""

import shutil
import sys
from pathlib import Path

import config as C

RUNTIME_FILES = ["config.py", "features.py", "infer_wav.py", "unoq_stream.py"]
ARTIFACT_FILES = ["model_int8.tflite", "labels.txt"]
DEFAULT_DEST = C.ROOT.parent / "python" / "edge_audio"

INIT_TEXT = '''"""
TinyAudioNet runtime for the Sound Guardian app (Arduino UNO Q).

GENERATED by edge_audio_mvp/deploy.py - do not edit here; edit edge_audio_mvp/
and run `python deploy.py` again. Needs only numpy and a TFLite interpreter
(tflite-runtime or ai-edge-litert); no TensorFlow.
"""
'''


def main():
    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DEST
    (dest / "artifacts").mkdir(parents=True, exist_ok=True)
    (dest / "logs").mkdir(exist_ok=True)

    for name in RUNTIME_FILES:
        shutil.copy2(C.ROOT / name, dest / name)
    missing = []
    for name in ARTIFACT_FILES:
        src = C.ARTIFACTS / name
        if src.exists():
            shutil.copy2(src, dest / "artifacts" / name)
        else:
            missing.append(str(src))
    (dest / "__init__.py").write_text(INIT_TEXT)
    (dest / "logs" / ".gitkeep").touch()

    print(f"deployed {len(RUNTIME_FILES)} runtime files + "
          f"{len(ARTIFACT_FILES) - len(missing)} artifacts -> {dest}")
    if missing:
        print("MISSING (train + quantize first): " + ", ".join(missing))
        return 1
    labels = (dest / "artifacts" / "labels.txt").read_text().split()
    size_kb = (dest / "artifacts" / "model_int8.tflite").stat().st_size / 1024
    print(f"model_int8.tflite {size_kb:.0f} KB, classes {labels}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
