"""
TinyAudioNet runtime for the Sound Guardian app (Arduino UNO Q).

GENERATED by edge_audio_mvp/deploy.py - do not edit here; edit edge_audio_mvp/
and run `python deploy.py` again. Needs only numpy and a TFLite interpreter
(tflite-runtime or ai-edge-litert); no TensorFlow.
"""
