"""
Build sketch/sketch.ino: a clean, standalone sketch that cycles through every
symbol of ../88_lighting_animated_rgb/88_lighting_animated_rgb.ino forever.

    python generate_sketch.py

Keeps from the main sketch: matrix config, colors, the 8x8 patterns, the
drawing helpers and every animate*() function. Drops: the Router Bridge, the
command handler, the standby switch and the original setup()/loop(). Then
appends a setup() that initialises the matrix and a loop() that plays all
animations in order. No commands, no serial input, no Bridge.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "88_lighting_animated_rgb" / "88_lighting_animated_rgb.ino"
OUT = HERE / "sketch" / "sketch.ino"

# animations in the order they are shown; anything the main sketch has that
# is not listed here is appended at the end automatically
ORDER = [
    ("animateShatter", "glass breaking"),
    ("animateSOS", "alarm"),
    ("animateSkull", "thud / fall"),
    ("animateVoice", "voice"),
    ("animateDanger", "unknown / danger"),
    ("animateQuestionMark", "question mark"),
    ("animateLoud", "loud sound"),
    ("animateCO", "carbon monoxide"),
    ("animateLightning", "electrical"),
    ("animateWater", "water / footsteps"),
    ("animateBat", "bat signal"),
    ("animateMorseSOS", "morse SOS"),
    ("animateLeft", "left arrow"),
    ("animateRight", "right arrow"),
]
SKIP = {"animateAll"}          # the DEMO cycle of the main sketch; we write our own
PAUSE_BETWEEN_MS = 600
PAUSE_BETWEEN_ROUNDS_MS = 1500
BRIGHTNESS = 15                # 0-255; overrides the main sketch's value for this app


def banner_before(text, idx):
    """Start of the '// ====' banner block that precedes position idx."""
    lines = text[:idx].split("\n")
    i = len(lines) - 1
    while i > 0 and not lines[i].startswith("// ====="):
        i -= 1
    while i > 0 and lines[i - 1].startswith("// "):
        i -= 1
    return len("\n".join(lines[:i]))


def main():
    src = SRC.read_text(encoding="utf-8")

    # 1. everything up to the command handler: config, colors, patterns, helpers, animations
    cut = src.index("void handleEvent(")
    head = src[:banner_before(src, cut)]

    # 2. remove the Router Bridge include and the STANDBY MODE block; set this app's brightness
    head = head.replace("#include <Arduino_RouterBridge.h>\n", "")
    head, n_bright = re.subn(r"^const uint8_t BRIGHTNESS = \d+;", f"const uint8_t BRIGHTNESS = {BRIGHTNESS};",
                             head, flags=re.M)
    if n_bright != 1:
        sys.exit("could not find the BRIGHTNESS line in the main sketch")
    head = re.sub(r"// =+\n// STANDBY MODE\n// =+\n.*?#define STANDBY_CYCLE \d+\n", "", head, flags=re.S)
    head = head.replace("// App Lab sends:\n//\n// Bridge.notify(\"sound_event\", \"GLASS\")\n//\n"
                        "// Router Bridge:\n// App Lab -> MCU -> RGB Matrix\n",
                        "// Standalone standby sketch: cycles every symbol, no Router Bridge,\n"
                        "// no commands. Generated by generate_sketch.py from\n"
                        "// 88_lighting_animated_rgb.ino - regenerate, do not edit here.\n")

    # 3. the colour assignments from the original setup()
    setup_start = src.index("void setup()")
    colors = re.findall(r"(\b[A-Z]+) =\s*\n\s*(matrix\.Color\([^)]*\));", src[setup_start:])
    if not colors:
        sys.exit("could not find the colour assignments in setup()")

    # 4. which animations exist
    defined = re.findall(r"^void (animate\w+)\(\)", head, flags=re.M)
    listed = [name for name, _ in ORDER if name in defined]
    extras = [name for name in defined if name not in listed and name not in SKIP]
    missing = [name for name, _ in ORDER if name not in defined]

    label = dict(ORDER)
    calls = "".join(
        f"  {name}();{' ' * max(1, 22 - len(name))}// {label.get(name, 'extra')}\n"
        f"  clearMatrix();\n  delay({PAUSE_BETWEEN_MS});\n\n"
        for name in listed + extras
    )
    color_lines = "".join(f"  {name} = {expr};\n" for name, expr in colors)

    tail = f"""
// ============================================================
// SETUP
// ============================================================

void setup() {{

  Serial.begin(115200);

  matrix.begin();
  matrix.setBrightness(BRIGHTNESS);

{color_lines}
  clearMatrix();

  Serial.println();
  Serial.println("================================");
  Serial.println(" SOUND GUARDIAN - SYMBOL CYCLE");
  Serial.println("================================");
  Serial.println("8x8 RGB matrix on pin {{LED_PIN}}: cycling all symbols");
  Serial.println();

  // startup indicator
  fillMatrix(GREEN);
  delay(250);
  clearMatrix();
}}


// ============================================================
// LOOP: every symbol, in order, forever
// ============================================================

void loop() {{

{calls}  delay({PAUSE_BETWEEN_ROUNDS_MS});
}}
""".replace("{LED_PIN}", "6")

    OUT.write_text(head.rstrip() + "\n\n" + tail, encoding="utf-8")

    print(f"wrote {OUT}: {len(listed) + len(extras)} animations")
    if extras:
        print("  appended (not in ORDER):", ", ".join(extras))
    if missing:
        print("  listed but not in the main sketch (skipped):", ", ".join(missing))
    code_tokens = ("Bridge.", "Arduino_RouterBridge", "handleEvent(", "soundEvent(", "STANDBY_CYCLE", "#if")
    leftovers = [w for w in code_tokens if w in OUT.read_text()]
    if leftovers:
        sys.exit(f"generated sketch still contains: {leftovers}")
    print("  no Bridge / command code left in the output")


if __name__ == "__main__":
    main()
